name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Python 3.11
      uses: actions/setup-python@v7
      with:
        python-version: "3.11"

    - name: Install pipenv
      run: pip install pipenv

    - id: cache-pipenv
      uses: actions/cache@v6
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pipenv install --dev

    - name: Run pyright
      run: pipenv run pyright

    - name: Run linters
      run: |
          pipenv run pre-commit run --all-files

